name = "Termbox"
badges = ["github-actions/ci.yaml", "metacpan"]
authority="cpan:SANKO"
module_maker="ModuleBuildTiny"
static_install = "auto"
license="artistic_2"
requires_external_bin=["make');my $make = can_run('make')//can_run('gmake'); chdir 'termbox';system $make.' install_lib prefix=\"../share\"';chdir '..';\n('1"]
markdown_maker = "Pod::Markdown::Github"

[release]
hook=[
    'tidyall -a'
]

[Metadata]
X_No_Archive = 'Yes'
