name = "Termbox"
badges = ["travis-ci.com", "metacpan"]
module_maker="ModuleBuildTiny"
static_install = "auto"
license="artistic_2"
authority="cpan:SANKO"
requires_external_bin=["cmake');`cmake ./termbox/ -DWITH_TRUECOLOR=1 -DBUILD_DEMOS=0 -DCMAKE_INSTALL_PREFIX=./share/;make;make install;`;\n('1"]

[release]
hook=[
    'tidyall -a'
]