name = "Termbox"
badges = ["github-actions/ci.yaml", "metacpan"]
module_maker="ModuleBuildTiny"
static_install = "auto"
license="artistic_2"
authority="cpan:SANKO"
requires_external_bin=["make');`make -C termbox2 prefix=../share install_lib`;\n('1"]
markdown_maker = "Pod::Markdown::Github"

[release]
hook=[
    'tidyall -a'
]

[Metadata]
X_No_Archive = 'Yes'
