name = "Termbox"
badges = ["travis-ci.com", "metacpan"]
module_maker="ModuleBuildTiny"
static_install = "auto"
license="artistic_2"
authority="cpan:SANKO"
requires_external_bin=["make');`cd termbox;make;make install prefix='../share';`;\n('1"]

[release]
hook=[
    'tidyall -a'
]
